{
 "title": "Graphcore IPU-POD16 Monitoring(v1.0)",
 "tags": [
  "Graphcore IPU-M2000",
  "ARM",
  "linux",
  "Ubuntu 18.04"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "IPU Logical Elements",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vipu_num_agents", "legendFormat": "Agents" },
    { "expr": "vipu_num_clusters", "legendFormat": "Clusters" },
    { "expr": "vipu_num_partitions", "legendFormat": "Partitions" }
   ]
  },
  {
   "title": "Number of Attached IPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum1:2112\",job=\"node\"})",
     "legendFormat": "IPUM1"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum2:2112\",job=\"node\"})",
     "legendFormat": "IPUM2"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum3:2112\",job=\"node\"})",
     "legendFormat": "IPUM3"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum4:2112\",job=\"node\"})",
     "legendFormat": "IPUM4"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",job=\"node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Power Usage of All Chassis(Watt)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(chassis_power{host=\"Graphcore IPU-M2000\",job=\"node\", psu_id=\"\" })",
     "legendFormat": "Total Power"
    }
   ]
  },
  {
   "title": "IPU-Tile Clock Speed(MHz)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ipu_tile_clk_speed) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IPU-M2000 Temperature(°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "avg(chassis_temperature) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chassis Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 6, "y": 14 },
   "targets": [
    { "expr": "avg(chassis_fan) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "IPU-Link Error Counts",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count(ipu_link_err_cnt) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Usage per IPU-M2000s(Watt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "chassis_power{host=\"Graphcore IPU-M2000\",job=\"node\", psu_id=\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}